# Generated by Django 2.2.4 on 2019-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("sdesc", models.CharField(max_length=500)),
                ("desc", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10000)),
                ("amount", models.PositiveIntegerField(default=0)),
                ("sold", models.PositiveIntegerField(default=0)),
                ("rating", models.PositiveSmallIntegerField(default=0)),
                ("img", models.FileField(default="noimage.jpg", upload_to="")),
            ],
        ),
    ]
