# Generated by Django 2.2.4 on 2019-09-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="username",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
