# Generated by Django 2.2.4 on 2019-09-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_review_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
