# Generated by Django 2.2 on 2019-08-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buyRecord',
            field=models.TextField(default=''),
        ),
    ]
