# Generated by Django 2.2.4 on 2019-08-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='buyRecord',
            new_name='record',
        ),
    ]
