# Generated by Django 2.2 on 2019-08-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_buyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='buyRecord',
            field=models.TextField(default=None),
        ),
    ]
