# Generated by Django 2.2.4 on 2019-09-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190910_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addresss',
            new_name='address',
        ),
    ]
