# Generated by Django 2.2 on 2019-08-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190807_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='buyRecord',
            field=models.TextField(),
        ),
    ]
