# Generated by Django 2.2 on 2019-08-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190807_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='buyRecord',
            field=models.TextField(blank=True),
        ),
    ]
