# Generated by Django 2.2.4 on 2019-08-08 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('items', models.TextField(default=None)),
                ('timeHis', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
