# Generated by Django 2.2.4 on 2019-08-30 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=100)),
                ('percent', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('items', models.TextField(default=None)),
                ('timeHis', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
